name: instash_scrapper
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  ## Architecture
  meta: ^1.8.0
  json_annotation: ^4.7.0
  chopper: ^6.0.0
  rxdart: ^0.27.7
  supercharged: ^2.1.1
  freezed: ^2.3.2
  hooks_riverpod: ^2.1.3
  auto_route: ^5.0.4
  get_it: ^7.2.0

  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  ## UI
  settings_ui: ^2.0.2
  fluent_ui: ^4.1.4
  flutter_acrylic: ^1.1.0+1
  window_manager: ^0.3.0
  pluto_grid: ^5.4.9
  cupertino_icons: ^1.0.5
  system_theme: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner:
  chopper_generator: ^6.0.0
  json_serializable: ^6.5.4
  swagger_dart_code_generator: ^2.9.0
  auto_route_generator: ^5.0.3
  flutter_gen_runner:
  very_good_analysis: ^3.1.0
  dart_code_metrics: ^5.4.0
  very_good_performance: ^0.0.4
  dependency_validator: ^3.2.2
  import_sorter: ^4.6.0
  hive_generator: ^2.0.0


scripts: derry.yaml

flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
